"""change type of last_seen

Revision ID: 383030f36fbf
Revises: 4a515676e817
Create Date: 2020-09-01 21:56:00.608180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383030f36fbf'
down_revision = '4a515676e817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_last_seen', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_last_seen', 'users', ['last_seen'], unique=1)
    # ### end Alembic commands ###
